baseURL = "https://wwww.macabine.bar/"
languageCode = "en-us"
title = "Ma cabine point barre."
theme = "gochowdown"
[permalinks]
posts = "/posts/:year/:month/:title"

[params]
favicon_32 = "/bigbelly-redimensionne.jpg" #FIXME
favicon = "/bigbelly-redimensionne.jpg" #FIXME
showNavTitle = "false"
favicon_16 = "/bigbelly-redimensionne.jpg" #FIXME: image not shown

[[menu.main]]
name = "Accueil"
weight = 1
url = "/"

[[menu.main]]
name = "Catégories"
weight = 2
url = "/catégories/"

[[menu.main]]
name = "Cuisine"
weight = 3
url = "/cuisine/"

[[menu.main]]
name = "Tags"
weight = 4
url = "/tags/"

[taxonomies]
"catégories" = "catégories"
cusine = "cuisine"
tag = "tags"
