baseURL = "https://www.macabine.bar"
languageCode = "en-us"
title = "Ma cabine point barre."
theme = "gochowdown"

[permalinks]
posts = "/posts/:year/:month/:title"

[params]
favicon_32 = "/assets/bigbelly-redimensionne.jpg"
favicon = "/assets/bigbelly-redimensionne.jpg"
favicon_16 = "/assets/bigbelly-redimensionne.jpg"
description = "Ici tu trouveras tout ce qu'il faut pour entretenir ta cabine"

[[menu.main]]
name = "Accueil"
weight = 1
url = "/"

[[menu.main]]
name = "Catégories"
weight = 2
url = "/catégories/"

[[menu.main]]
name = "Tags"
weight = 3
url = "/tags/"

[taxonomies]
"catégories" = "catégories"
tag = "tags"

[outputs]
home = ["json", "html"]
