name: publish

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  publish:
    # Name the Job
    name: publish
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Check docker installed
        run: |
          docker -v
        working-directory: /home/
      - name: Checkout gh-pages branch
        run: |
          git clone https://github.com/jbebar/macabine.git macabine-build
          cd macabine-build
          git checkout gh-pages
        working-directory: /home/runner/work/macabine
      - name: Build website
        run: |
          hugo --source ./macabine --destination /home/runner/work/macabine/macabine-build
        working-directory: /home/runner/work/macabine
      - name: Push to gh-pages branch
        run: |
          ls -a
          git status
          git config --global user.name "ci-bot"
          git remote set-url --push origin https://jbebar:${{ secrets.GITHUB_TOKEN }}@github.com/jbebar/macabine.git
          git commit -am "Update site"
          git push --set-upstream origin gh-pages
        working-directory: /home/runner/work/macabine/macabine-build
