name: publish

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  publish:
    # Name the Job
    name: publish
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout previous build
        run: |
          git clone https://github.com/jbebar/macabine.git macabine-build
          cd macabine-build
          git checkout gh-pages
        working-directory: /home/runner/work/macabine
      - name: Clean previous build
        run: ls | xargs -d"\n" rm -rf
        working-directory: /home/runner/work/macabine/macabine-build
      - name: Build website in build directory
        run: docker run -v /home/runner/work/macabine:/mnt klakegg/hugo "--source /mnt/macabine --destination /mnt/macabine-build"
        working-directory: /home/runner/work/macabine
      - name: Push build to gh-pages branch
        run: |
          git config --global user.name "ci-bot"
          git remote set-url --push origin https://jbebar:${{ secrets.GITHUB_TOKEN }}@github.com/jbebar/macabine.git
          git status --porcelain
          export status=git status --porcelain | wc -l
          if [ $status != "0" ]; then git commit -m "Update site" && git push --set-upstream origin gh-pages; fi;          
        working-directory: /home/runner/work/macabine/macabine-build
